server:
  port: ${PORT:8080}   # Railway o‘zi port beradi
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres.railway.internal:5432/railway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:sWlsxZRCzfOTvCeFURhkkkgVHAsxYpBO}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:60000}
      database: ${REDIS_DB:0}

security:
  jwt:
    key: ${JWT_SECRET_KEY:WC+qbHYl2B0o02421L+2UayDp2LtczY/3cSkAyErfTjmcEOXNtyjXq0un/SdY4cw}
    issuer: ${JWT_ISSUER:https://secure-java-sayd.com}
    expiration: ${JWT_EXPIRATION:259200000}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    persistAuthorization: true
